### ISSUE TITLE
MatLab error upon launch

### ISSUE THREAD

**Issue by tbeardx** [diffplug/matlabcontrol#12]
I'm running the latest build of matconsolectl in NetBeans 8.1 on a network without internet access.  I have removed the test packages from the project (so it's not trying to reference JUNIT) and removed the reference to <b>edu.umd.cs.findbugs.annotations.SuppressFBWarnings</b>.

Matlab is throwing an error after launch via the Connect button:  Undefined variable "matlabcontrol" or class "matlabcontrol.MatlabClassLoaderHelper.ConfigureClassLoading"

Did I miss something in the setup?  Or is this related to my removal of a reference?

**Comment by nedtwigg** [comment]
Sounds like you're compiling from scratch instead of the downloaded jar?  In the README, we have this example, which downloads the single jar and runs the DemoMain application.

``` matlab
version = '4.4.2';
tempdir = 'matconsolectl_demo';

% make a directory to copy the jar into
mkdir(tempdir);
% download the jar
URL = ['https://repo1.maven.org/maven2/com/diffplug/matsim/matconsolectl/' version '/matconsolectl-' version '.jar'];
filename = [tempdir '/matconsolectl-' version '.jar'];
websave(filename,URL);
% add it to the path
javaaddpath([pwd '\' tempdir]);

% run it
matlabcontrol.demo.DemoMain
```

Sounds like you're doing something more complicated.  We'll need a more detailed description of what you're doing - you shouldn't need to remove any code to make this work.

**Comment by nedtwigg** [comment]
Might wanna take a look at #4 as well.

**Comment by tbeardx** [comment]
I did acquire the jar from Maven and when running the demo directly from the jar, everything works fine.  But now I need to be able to compile from scratch.  I've been tasked to build a Java based framework and GUI for reaching out to our various tools.  One of the larger toolsets is in Matlab.  So it would seem that I need to be able to fold the matconsolectl code into my own program.

After opening the project in netbeans, I was getting immediate errors because the project was referencing packaging I didn't have (JUNIT and the findbugs mentioned in the original post).  The JUNIT references were completely confined to the test packages, so I simply removed them from the project.  I commented out the couple lines that referenced findbugs (assuming that wouldn't have serious impact).

#4 wasn't too helpful.  I tried to run the gradlew.bat file, but get new errors there because I'm working on a system with no internet connection.

**Comment by nedtwigg** [comment]
Gotcha.  I don't think this is an issue related to MatConsoleCtl, I think it's about getting your tools to work in an offline environment.  MatConsoleCtl is used widely in offline environments, so I don't think the problem lies there.

All I can say is that I highly recommend that you don't work from the sourcecode directly, and instead link to the compiled jar, source jar, and javadoc.

**Comment by tbeardx** [comment]
Thanks.  I didn't realize that was an option.  I'll explore that further.

**Comment by tbeardx** [comment]
Well, you were right.  Link to the jar did it.  As a test I built my own version of <b>DemoMain.java</b> to call the <b>DemoFrame</b> and it worked.  It was even able to connect to Matlab and send commands without issue.
