### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by kusan-reveur** [diffplug/matlabcontrol#7]
Hi,

Is there any way to make it work on a remote network (not local)?

Thank you in adance.

**Comment by nedtwigg** [comment]
It is possible, but tricky.  MATLAB is running `MatlabConnector`, and the remote java code is running `RemoteMatlabProxy`.  In order to initialize, there are a few details which have to be manually coordinated.  MatConsoleCtl has lots of mechanisms for sharing these details locally (e.g. Matlab starts the java code, or Java starts the Matlab code, or manually copy-pasting something).  If you want to coordinate remote machines, then you're on your own as far as how to transfer these details.

Here's the initialization sequence:
- Outside of MATLAB, [`RemoteMatlabProxyFactory`](https://github.com/diffplug/matconsolectl/blob/ffb79c619f95c75de61919a6d2c24b776745e586/src/matlabcontrol/RemoteMatlabProxyFactory.java) creates a random receiver ID.
- If the computer doesn't have an RMI registry yet, it creates one on a specified port.
- Now inside MATLAB, someone has to call [`MatlabConnector.connectFromMatlab`](https://github.com/diffplug/matconsolectl/blob/ffb79c619f95c75de61919a6d2c24b776745e586/src/matlabcontrol/MatlabConnector.java#L100-L110) and pass the receiver ID and port as arguments.  With a remote machine, I'm not sure how you will communicate what the receiver ID and port will be.  I guess you can agree on constants ahead of time, but MatConsoleCtl currently only allows setting the port manually, the receiver ID is always random.  That could be changed.

The other problem is that currently the RMI registry is only bound to localhost.  It's possible to change this, or to use a port forwarding utility to connect two localhosts together.

Are you wishing to run a fleet of MATLAB instances controlled by one remote application?

**Comment by kusan-reveur** [comment]
Thanks. I howeever decided to start the Server directly in Matlab, more simple.
I wanted to do it remotely because I have to start Matlab on a remote disk (the "Start In" features on Windows shortcut). I just made shortcut which start a matlab and run a script to run the java class.

**Comment by nedtwigg** [comment]
Good call!
